### ISSUE TITLE
Donate >> Click on contact button, User is navigated to GitHub OnionBrowser issues

### ISSUE THREAD

**Issue by Nishant-Taksande** [OnionBrowser/onionbrowser.github.io#18]
**Link:**
https://guardianproject.github.io/onionbrowser-website-dev/

**Steps To Reproduce:**

1. Click on above link
2. Click on donate button
3. Click on contact button
4. Verify page

**Expected:**
Contact Page should be opened

**Actual:**
User is navigated to GitHub OnionBrowser issues

**Video**:
https://monosnap.com/file/z6ZSXgbIe67lcxyQbFFKcrwpk1Myfq

**Comment by 8pen-s8urce** [comment]
I think that this is intended behaviour because I don't see any contact page on the Onion Browser website.

If this isn't intended behaviour, the Guardian Project has a contact page on its website that the Onion Browser website can link to.

The Guardian Project contact page: https://guardianproject.info/contact/

**Comment by tladesignz** [comment]
True. We'll leave it like that.
